<?php
$this->title = utf8_encode("Cadastro de Universidade");
$this->headTitle($this->title);
?>
<script type="text/javascript" src="<?php print $this->baseUrl() . '/js/universidades/novo.js' ?>"></script>
<form name="form" id="form" id="universidade" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array('action'=>'novo'));?>" method="post">
    <table id="tbFormUniversidades" style="width: 100%;">
        <tr>
            <td>
                <label for="nome">Nome:</label>
            </td>
            <td>
                <div id="inputNome" class="control-group">
                    <label class="control-label" for="nome"><span class="label label-important">Erro</span>&nbsp;&nbsp;Campo Nome Obrigat&oacute;rio</label>
                    <div class="controls">
                        <input type="text" name="nome" id="nome" class="input" autocomplete="off" value="" placeholder="Informe o nome..."><br />
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="aRight">
                <input type="submit" name="cancelar" id="btCancelar" value="Cancelar" class="btn btn-primary">&nbsp;&nbsp;
                <input type="button" name="cadastrar" id="btCadastrar" value="Cadastrar" class="btn btn-primary">
            </td>
        </tr>
    </table>
</form>