<?php
$this->title = utf8_encode("Cadastro de Alunos");
$this->headTitle($this->title);
?>
<script type="text/javascript" src="<?php print $this->baseUrl() . '/js/alunos/novo.js' ?>"></script>
<form name="form" id="cursos" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array('action'=>'novo'));?>" method="post">
    <input type="hidden" name="ajax" id="ajax" value="<?php echo $this->url(array('action' => 'get-ajax-content', 'format' => 'json'))?>"  />
    <table id="tbFormCursos" style="width: 100%;">
        <tr>
            <td>
                <label for="universidadeId">Universidade:</label>
            </td>
            <td>
                <div id="selectUniversidadeId" class="control-group">
                    <div class="controls">
                        <?php if($this->selectUniversidades!="") : ?>
                        <select name="universidade_id" id="universidadeId" class="select">
                            <option value=""></option>
                            <optgroup label="Selecione uma universidade abaixo..." >
                            <?php foreach ($this->selectUniversidades as $key => $value) :?>
                                <option value="<?php print $key?>"><?php print $key.' - '.$value?></option>
                            <?php endforeach;?>
                            </optgroup>
                        </select>
                        <?php else :?>
                            <div class="alert alert-info">
                                N&atilde;o h&aacute; universidades cadastradas.&nbsp;&nbsp;<i class="icon-hand-right"></i>&nbsp;&nbsp;<a class="btn btn-primary btn-large" href="<?php echo $this->url(array('controller'=>'universidades','action'=>'novo'));?>">Cadastrar Universidade</a>
                            </div>
                        <?php endif;?>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label for="cursoId">Curso:</label>
            </td>
            <td>
                <div id="selectCursoId" class="control-group" style="position: relative;">
                    <label class="control-label" for="cursoId"><span class="label label-important">Erro</span>&nbsp;&nbsp;Campo Curso Obrigat&oacute;rio</label>
                    <div class="controls" style="position: relative;">
                        <select name="curso_id" id="cursoId" class="select"></select>
                        <div id="mensagem" style="display: none;position: absolute;width:93%;top: -15px;" class="alert alert-info"></div>
                    </div>
                    <img border="0" align="absmiddle" style="position:absolute;float: left;top: 7px;display: none;" id="load" alt="" src=" <?php print $this->baseUrl() .'/images/ajax-loader_pequeno.gif'?>">
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label for="matricula">Matricula:</label>
            </td>
            <td>
                <div id="inputMatricula" class="control-group">
                    <label class="control-label" for="nome"><span class="label label-important">Erro</span>&nbsp;&nbsp;Campo Matricula Obrigat&oacute;rio</label>
                    <div class="controls">
                        <input type="text" name="matricula" id="matricula" class="input" autocomplete="off" value="" placeholder="Informe a matricula..."><br />
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label for="nome">Nome:</label>
            </td>
            <td>
                <div id="inputNome" class="control-group">
                    <label class="control-label" for="nome"><span class="label label-important">Erro</span>&nbsp;&nbsp;Campo Nome Obrigat&oacute;rio</label>
                    <div class="controls">
                        <input type="text" name="nome" id="nome" class="input" autocomplete="off" value="" placeholder="Informe o nome..."><br />
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="aRight">
                <input type="submit" name="cancelar" id="btCancelar" value="Cancelar" class="btn btn-primary">&nbsp;&nbsp;
                <input type="button" name="cadastrar" id="btCadastrar" value="Cadastrar" class="btn btn-primary">
            </td>
        </tr>
    </table>
</form>