<?php
$this->title = utf8_encode("Editar Cursos");
$this->headTitle($this->title);
?>
<script type="text/javascript" src="<?php print $this->baseUrl() . '/js/cursos/editar.js' ?>"></script>
<form name="form" id="cursos" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array('action'=>'editar'));?>" method="post">
    <input type="hidden" name="id" value="<?php echo $this->oCursos['id'];?>" />
    <table id="tbFormCursos" style="width: 100%;">
        <tr>
            <td>
                <label for="universidadeId">Universidade:</label>
            </td>
            <td>
                <div id="selectUniversidadeId" class="control-group">
                    <label class="control-label" for="nome"><span class="label label-important">Erro</span>&nbsp;&nbsp;Campo Universidade Obrigat&oacute;rio</label>
                    <div class="controls">
                        <select name="universidade_id" id="universidadeId" class="select">
                            <option value=""></option>
                            <optgroup label="Selecione uma universidade abaixo..." >
                            <?php foreach ($this->selectUniversidades as $key => $value) :?>
                                <option value="<?php print $key?>" <?php print $this->oCursos['universidade_id'] == $key ? 'selected ' : '' ?> ><?php print $key.' - '.$value?></option>
                            <?php endforeach;?>
                            </optgroup>
                        </select>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label for="nome">Nome:</label>
            </td>
            <td>
                <div id="inputNome" class="control-group">
                    <label class="control-label" for="nome"><span class="label label-important">Erro</span>&nbsp;&nbsp;Campo Nome Obrigat&oacute;rio</label>
                    <div class="controls">
                        <input type="text" name="nome" id="nome" class="input" autocomplete="off" value="<?php echo $this->oCursos['nome'];?>" placeholder="Informe o nome..."><br />
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="aRight">
                <input type="submit" name="cancelar" id="btCancelar" value="Cancelar" class="btn btn-primary">&nbsp;&nbsp;
                <input type="button" name="salvar" id="btSalvar" value="Salvar" class="btn btn-success">
            </td>
        </tr>
    </table>
</form>