<?php
$this->title = utf8_encode("Cadastro de Cursos");
$this->headTitle($this->title);
?>
<script type="text/javascript" src="<?php print $this->baseUrl() . '/js/cursos/novo.js' ?>"></script>
<form name="form" id="cursos" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array('action'=>'novo'));?>" method="post">
    <table id="tbFormCursos" style="width: 100%;">
        <tr>
            <td>
                <label for="universidadeId">Universidade:</label>
            </td>
            <td>
                <div id="selectUniversidadeId" class="control-group">
                    <label class="control-label" for="universidadeId"><span class="label label-important">Erro</span>&nbsp;&nbsp;Campo Universidade Obrigat&oacute;rio</label>
                    <div class="controls">
                        <?php if($this->selectUniversidades!="") : ?>
                        <select name="universidade_id" id="universidadeId" class="select">
                            <option value=""></option>
                            <optgroup label="Selecione uma universidade abaixo..." >
                            <?php foreach ($this->selectUniversidades as $key => $value) :?>
                                <option value="<?php print $key?>"><?php print $key.' - '.$value?></option>
                            <?php endforeach;?>
                            </optgroup>
                        </select>
                        <?php else :?>
                            <div class="alert alert-info">
                                N&atilde;o h&aacute; universidades cadastradas.&nbsp;&nbsp;<i class="icon-hand-right"></i>&nbsp;&nbsp;<a class="btn btn-primary btn-large" href="<?php echo $this->url(array('controller'=>'universidades','action'=>'novo'));?>">Cadastrar Universidade</a>
                            </div>
                        <?php endif;?>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label for="nome">Nome:</label>
            </td>
            <td>
                <div id="inputNome" class="control-group">
                    <label class="control-label" for="nome"><span class="label label-important">Erro</span>&nbsp;&nbsp;Campo Nome Obrigat&oacute;rio</label>
                    <div class="controls">
                        <input type="text" name="nome" id="nome" class="input" autocomplete="off" value="" placeholder="Informe o nome..."><br />
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="aRight">
                <input type="submit" name="cancelar" id="btCancelar" value="Cancelar" class="btn btn-primary">&nbsp;&nbsp;
                <input type="button" name="cadastrar" id="btCadastrar" value="Cadastrar" class="btn btn-primary">
            </td>
        </tr>
    </table>
</form>